# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comfort', models.FloatField(default=0.0)),
                ('stubbornness', models.FloatField(default=0.0)),
                ('neighbors', models.TextField(default='')),
                ('offeror_values', models.TextField(default='')),
                ('acceptor_values', models.TextField(default='')),
                ('offeror_count', models.IntegerField(default=0)),
                ('acceptor_count', models.IntegerField(default=0)),
                ('offeror_success', models.IntegerField(default=0)),
                ('acceptor_success', models.IntegerField(default=0)),
                ('offeror_failure', models.IntegerField(default=0)),
                ('acceptor_failure', models.IntegerField(default=0)),
                ('offeror_positive_loss', models.FloatField(default=0)),
                ('offeror_negative_loss', models.FloatField(default=0)),
                ('acceptor_positive_loss_count', models.IntegerField(default=0)),
                ('acceptor_negative_loss_count', models.IntegerField(default=0)),
                ('offeror_positive_loss_count', models.IntegerField(default=0)),
                ('offeror_negative_loss_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='uservalues',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
