# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 18:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20171111_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comfort', models.FloatField(default=0.0)),
                ('stubbornness', models.FloatField(default=0.0)),
                ('neighbors', models.TextField(default='')),
                ('offeror_values', models.TextField(default='')),
                ('acceptor_values', models.TextField(default='')),
                ('offeror_count', models.IntegerField(default=0)),
                ('acceptor_count', models.IntegerField(default=0)),
                ('offeror_success', models.IntegerField(default=0)),
                ('acceptor_success', models.IntegerField(default=0)),
                ('offeror_failure', models.IntegerField(default=0)),
                ('acceptor_failure', models.IntegerField(default=0)),
                ('offeror_positive_loss', models.FloatField(default=0)),
                ('offeror_negative_loss', models.FloatField(default=0)),
                ('acceptor_positive_loss_count', models.IntegerField(default=0)),
                ('acceptor_negative_loss_count', models.IntegerField(default=0)),
                ('offeror_positive_loss_count', models.IntegerField(default=0)),
                ('offeror_negative_loss_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
