# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_robots'),
    ]

    operations = [
        migrations.AddField(
            model_name='robots',
            name='image_id',
            field=models.IntegerField(default=1),
        ),
    ]
