# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20171112_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='robots',
            name='acceptor_negative_loss',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='robots',
            name='acceptor_positive_loss',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='uservalues',
            name='acceptor_negative_loss',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='uservalues',
            name='acceptor_positive_loss',
            field=models.FloatField(default=0),
        ),
    ]
