# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20171113_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservalues',
            name='user_acceptor_values',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='uservalues',
            name='user_offeror_values',
            field=models.TextField(default=''),
        ),
    ]
