# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservalues',
            name='last_robot_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='files/'),
        ),
    ]
