# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20171222_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robots',
            name='user_acceptor_failure',
        ),
        migrations.RemoveField(
            model_name='robots',
            name='user_acceptor_success',
        ),
        migrations.RemoveField(
            model_name='robots',
            name='user_offeror_failure',
        ),
        migrations.RemoveField(
            model_name='robots',
            name='user_offeror_success',
        ),
        migrations.AddField(
            model_name='uservalues',
            name='user_acceptor_failure',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uservalues',
            name='user_acceptor_success',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uservalues',
            name='user_offeror_failure',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uservalues',
            name='user_offeror_success',
            field=models.IntegerField(default=0),
        ),
    ]
